{% set name = "opendatasets" %}
{% set version = "0.1.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opendatasets-{{ version }}.tar.gz
  sha256: 52b2e0c1cc80d9f44842e3373532d92683f7c0f5c3e72b3f1f3e2750d30da4db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tqdm
    - kaggle
    - click

test:
  imports:
    - opendatasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JovianML/opendatasets
  summary: A curated collection of datasets for data analysis & machine learning, downloadable with a single Python command
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/JovianHQ/opendatasets

extra:
  recipe-maintainers:
    - piterand
